version: '3.0'
services:
  app:
    command: yarn dev
    # image: divante/vue-storefront-api:latest
    build:
      context: .
      dockerfile: docker/vue-storefront-api/Dockerfile
    depends_on:
      - es1
      - redis
    env_file: docker/vue-storefront-api/default.env
    volumes:
      - './migrations:/var/www/migrations'
      - './scripts:/var/www/scripts'
      - './src:/var/www/src'
    tmpfs:
      - /var/www/dist
    ports:
      - '8080:8080'
      - '9222:9222'
